server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: 43.142.97.59:8848
    sentinel:

      # sentinel 持久化规则
      datasource:
        ds1:
          nacos:
            server-addr: 43.142.97.59:8848  # nacos地址
            dataId: ${spring.application.name}  # 配置文件的文件名
            groupId: DEFAULT_GROUP   # 哪一个组
            data-type: json  # 文件格式
            rule-type: flow  # 规则类型，这里是流控类型



      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'